[IN-115][Reviews] Add preprint doi pending minting message
CenterForOpenScience/ember-osf-reviews pull request #114
Opened 2018-02-05 15:21 UTC by adlius

## Purpose

Fix the problem that preprint detail page for moderation shows the link for DOI before it is minted.

## Summary of Changes

Add conditionals in `preprint-detail.hbs` to watch for `preprintDoiCreated`.

## Side Effects / Testing Notes

None.

## Ticket

https://openscience.atlassian.net/browse/IN-115

2018-02-09 16:46 UTC, baylee-d requested changes
Just some small formatting changes and a question on one of the variables.  Other than that, it looks good.

2018-02-09 16:46 UTC, baylee-d commented on app/templates/preprints/provider/preprint-detail.hbs
> +                                    <p> {{t "content.preprintPendingDOIMinted"}} </p>
You probably don't need spaces between the `<p>` and `{{` on lines 98 or 99 here

2018-02-09 16:46 UTC, baylee-d commented on app/templates/preprints/provider/preprint-detail.hbs
> +                                {{#if preprintDoiCreated}}
Where is `preprintDoiCreated` being declared?  Or is it an attribute in the model?

2018-02-22 18:40 UTC, alexschiller approved these changes
LGTM 🔍 🚐

2018-04-12 13:08 UTC, alexschiller requested changes
I changed the branch to next-interfaces. Can you add the CHANGELOG please?

2018-04-12 19:19 UTC, alexschiller approved these changes

2018-04-12 19:20 UTC, merged