[IN-477]Make sure Reviews work with post-NPD changes
CenterForOpenScience/ember-osf-reviews pull request #153
Opened 2018-10-04 21:15 UTC by adlius

## Purpose

To maintain functional parity with `ember-osf-preprints` once NPD changes are in effect.

## Summary of Changes/Side Effects

Placeholder

## Testing Notes

Placeholder

## Ticket

https://openscience.atlassian.net/browse/IN-477

# Reviewer Checklist

- [ ] meets requirements
- [ ] easy to understand
- [ ] DRY
- [ ] testable and includes test(s)
- [ ] changes described in `CHANGELOG.md`

2018-10-22 21:01 UTC, pattisdr requested changes
Thanks for addressing these reviews changes @adlius!

Just a few things that could be removed, and then where we were checking to see if a node was public, we should check the preprint instead.

2018-10-22 21:01 UTC, pattisdr commented on app/components/preprint-file-browser/component.js
>      selectedFile: null,
This can probably be removed

2018-10-22 21:01 UTC, pattisdr commented on app/controllers/preprints/provider/moderation.js
> -                node_is_public: true,
~If you were previously querying preprints here whose node was public, I guess we should change to preprints who are public.~

Edited: Nevermind, looks like reviewers preprints queryset already removes private preprints.

2018-10-22 21:01 UTC, pattisdr commented on app/controllers/preprints/provider/preprint-detail.js
> -        if (!node.get('public')) {
If the preprint itself is private, it will break the page.  I would try catching a 403 after findRecord
```
const response = yield this.get('store').findRecord(
            'preprint',
            preprintId,
            { include: ['node', 'license', 'review_actions', 'contributors'] },
        ).catch(() => this.replaceWith('page-not-found'));
```

2018-10-22 21:01 UTC, pattisdr commented on app/components/preprint-file-browser/component.js
>      pageNumber: 0,
This can probably be removed.

2018-10-22 21:01 UTC, pattisdr commented on app/controllers/preprints/provider/preprint-detail.js
> -        },
In addition, activeFile and chosenFile above could probably be removed?

2018-10-26 03:09 UTC, pattisdr approved these changes
Looks good to me @adlius!

2018-11-05 15:07 UTC, pattisdr commented
@adlius, @jamescdavis, checking in on this one.  Can we get these reviews changes on staging3? I assume this needs to go out with NPD.

2018-11-12 20:33 UTC, pattisdr commented
@brianjgeiger, can this go on staging3?

2018-11-13 00:39 UTC, jamescdavis approved these changes
LGTM!

2018-11-13 00:40 UTC, merged

2018-11-13 00:41 UTC, pattisdr commented
thank you @jamescdavis!