[MOD-175][Hotfix] Include api version in queryHasMany request
CenterForOpenScience/ember-osf-reviews pull request #86
Opened 2017-11-01 20:10 UTC by laurenbarker

## Purpose
Prevent timezone issues.

## Changes
* Included header with api version in queryHasMany request.
    * Used version 2.5 because I get errors with 2.6
* Updated accessing the metadata since it changed between API version.

## Side effects
None expected.

2017-11-01 20:17 UTC, aaxelb requested changes
Out of curiosity, what errors did you get with 2.6?

2017-11-01 20:17 UTC, aaxelb commented on app/services/store.js
> +                        ACCEPT: 'application/vnd.api+json; version=2.5',
Could you import `ember-osf/adapters/osf-adapter` and use its `headers` instead?

2017-11-01 20:25 UTC, laurenbarker commented
500 from the API:
```
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
[01/Nov/2017 15:23:55] "GET /v2/preprint_providers/osf/preprints/?filter%5Breviews_state%5D=accepted&filter%5Bnode_is_public%5D=true&meta%5Breviews_state_counts%5D=true&sort=-date_last_transitioned&page=1 HTTP/1.1" 500 59
```

2017-11-01 20:52 UTC, laurenbarker commented on app/services/store.js
> +                        ACCEPT: 'application/vnd.api+json; version=2.5',
Tried and failed to import the headers as discussed on flowdock 😞 . Added ticket and comment.

2017-11-02 13:23 UTC, aaxelb approved these changes

2017-11-02 13:23 UTC, merged